# Site settings
title: Josh Sadler
email: joshsadler@me.com
description: "UX designer at Fintech company, Jack Henry & Associates, living in Cedar Falls, Iowa."
baseurl: ""
url: "http://www.joshsadler.co"
twitter_username: joshsadler
github_username:  joshsadler

# Build settings
markdown: kramdown

sass:
  style: :compressed

permalink: pretty
paginate: 5

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']